on:
  issue_comment:
    types: [created]
jobs:
  BuildCandidate:
    if: startsWith( github.event.comment.body, 'rebuild')
    runs-on: ubuntu-latest    
    steps:
     - uses: actions/checkout@v3
       with:
         persist-credentials: false
     - name: something
       run: |
         echo ${{ github.event.comment.body }}
